### PR TITLE
Improve performance of Rendering Arrays exercise

### PR DESCRIPTION
**Pull request by aaronccasanova**
Reduces the number of operations performed by the `addItem` function in the  `Rendering Arrays` exercise.  While this "improvement" is quite trivial, I also feel that the update slightly improves readability.

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Sure! Thanks 😊

**Comment by kentcdodds** [comment]
@All-contributors please add @aaronccasanova for code

**Comment by kentcdodds** [comment]
@all-contributors please add @aaronccasanova for code

**Comment by kentcdodds** [comment]
Weird, the bot seems to not be working right now. Will try again tomorrow

**Comment by aaronccasanova** [comment]
Awesome! Wow, you're on it!

Not sure if it matters, but I forgot to assign myself to the PR and couldn't edit it after the fact.

Also, I just realized I probably should have updated `src/final/07.js` as well. I can get in another quick PR for that. Thoughts?

> Weird, the bot seems to not be working right now. Will try again tomorrow

Hmm that is odd. For sure, thanks!

**Comment by kentcdodds** [comment]
Oh right! Yeah, another PR would be welcome

**Pull request merged**
