### PR TITLE
chore: update React imports

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @MichaelDeBoey for code

**Comment by Segebre** [comment]
Should we opt for using `import * as React from 'react'` over `import React from 'react'` every time? 😳

**Comment by kentcdodds** [comment]
Yes. I've made an alias for this 😅

```javascript
"import React": {
  "prefix": "ir",
  "body": ["import * as React from 'react'\n"]
},
```

For more info: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

**Pull request merged**
