### PR TITLE
Add 'root' id to root element to replicate the base exercise.

### PR DESCRIPTION
**Pull request by rchinerman**
In the base exercise, we have an id of "root" on the div, and in the extra credit we are supposed to programmatically reproduce this element, so I thought it made sense to also replicate the root id.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hi @rchinerman,

I think that's perfectly reasonable. But I'm not going to merge this because it's not in the video and it's not actually necessary. The only reason the ID was there in the first place was to make it easy to select from our JavaScript.

Thanks anyway!

**Comment by rchinerman** [comment]
While I agree it's not necessary, it actually is in the video. image

**Comment by kentcdodds** [comment]
lol 🤦‍♂️

Ok, I take it back. Let's merge this thing!

**Comment by kentcdodds** [comment]
@all-contributors please add @rchinerman for code

**Comment by kentcdodds** [comment]
Thanks for your patience with me :)

**Pull request merged**
