### PR TITLE
Updates node engine

### LINKED ISSUE #48: Project validation error while setting up the projecct
Hello, Am getting the following ES Lint error when I run the setup. Please advise.

 Am using node version v10.10.0
and 
npm --version 6.4.1
---------------
    ▶️  Starting: Project Validation
          Running validation checks to ensure dependencies were installed properly
          Running the following command: npm run validate -s

Oops! Something went wrong! :(

ESLint: 7.10.0

TypeError: createRequire is not a function
Referenced from: ~/code/epicreact/react-fundamentals/package.json
    at Object.resolve (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/shared/relative-module-resolver.js:40:20)
    at ConfigArrayFactory._loadExtendedShareableConfig (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/config-array-factory.js:872:39)
    at ConfigArrayFactory._loadExtends (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/config-array-factory.js:776:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/config-array-factory.js:715:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/config-array-factory.js:508:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:367:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (~/code/epicreact/react-fundamentals/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:288:18)
    🚨  Failure: Project Validation. Please review the messages above for information on how to troubleshoot and resolve this issue.

### PR DESCRIPTION
**Pull request by PritamSangani**
Updates required node version to >=10.13 to match that of the react-workshop-app. Makes changes required to fix #48

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @PritamSangani for code

**Comment by PritamSangani** [comment]
@kentcdodds No worries! I am happy to make the required changes to the rest of the repos if that is ok with you?

**Comment by kentcdodds** [comment]
That would be welcome @PritamSangani!

**Comment by PritamSangani** [comment]
Done!

**Comment by kentcdodds** [comment]
Thank you :)

**Pull request merged**
