### PR TITLE
docs(ex-06): add link to MDN Event.preventDefault

### PR DESCRIPTION
**Pull request by oscard0m**

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Great idea!

**Comment by kentcdodds** [comment]
@all-contributors please add @oscard0m for docs

**Comment by kentcdodds** [comment]
😂 I keep doing that.

**Comment by oscard0m** [comment]
> 😂 I keep doing that.

I was going to ask if you automated allcontributions comment or not 🤣

**Comment by kentcdodds** [comment]
It's just that I have so many repos and so many people contributing it's hard to remember who's done what unless I look it up first 🙃

**Comment by oscard0m** [comment]
> It's just that I have so many repos and so many people contributing it's hard to remember who's done what unless I look it up first 🙃

Of course. No problem.

Would you see valuable if `all-contributors` GitHub App manages merged PR's for you? I just opened [an issue](url) to `all-contributors`

**Comment by kentcdodds** [comment]
Yeah, that could be handy. The problem is the bot knowing what kinds of contributions were made. Even contributions in source files would be documentation if it's code comments (like this contribution).

**Comment by oscard0m** [comment]
> Yeah, that could be handy. The problem is the bot knowing what kinds of contributions were made. Even contributions in source files would be documentation if it's code comments (like this contribution).

Yep... that's what come up to my mind when writing the issue. Feel free to participate there. I was considering semantic-commits syntax like... 
if merge has semantic-commit syntax and it can map type of contributions, run automatically.

**Comment by kentcdodds** [comment]
The idea of using the commit message would be really awesome 👍

**Pull request merged**
