### PR TITLE
Fix: Removing className as props from Box component - 05-Extra 2

### PR DESCRIPTION
**Pull request by ASPzoomin**
**2. 💯 accept a size prop to encapsulate styling.  ------- 5th Assignment extra credit 2**

For this challenge we are sending **size** as props to **Box component** so **className** is no longer necessary and it's not being used.

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
That sounds fine. Thanks 👍

**Comment by kentcdodds** [comment]
@all-contributors please add @ASPzoomin for code

**Comment by jmurphyau** [comment]
`node setup` fails after this change

```
  12:25  error  'className' is not defined  no-undef
```

**Comment by kentcdodds** [comment]
Thank you! I should've caught that. Fixed!

**Comment by kentcdodds** [comment]
@All-contributors please add @jmurphyau for bugs

**Pull request merged**
